# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interval_set_checking_mode <- function(mode) {
    invisible(.Call(`_boostedintervals_interval_set_checking_mode`, mode))
}

interval_get_checking_mode <- function() {
    .Call(`_boostedintervals_interval_get_checking_mode`)
}

interval_get_rounding_mode <- function() {
    .Call(`_boostedintervals_interval_get_rounding_mode`)
}

interval_set_rounding_mode <- function(mode) {
    .Call(`_boostedintervals_interval_set_rounding_mode`, mode)
}

interval_rounding_constant <- function(mode) {
    .Call(`_boostedintervals_interval_rounding_constant`, mode)
}

interval_rounding_name <- function(mode) {
    .Call(`_boostedintervals_interval_rounding_name`, mode)
}

interval_add <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_add`, lower1, upper1, lower2, upper2)
}

interval_subtract <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_subtract`, lower1, upper1, lower2, upper2)
}

interval_multiply <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_multiply`, lower1, upper1, lower2, upper2)
}

interval_divide <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_divide`, lower1, upper1, lower2, upper2)
}

interval_exp <- function(lower, upper) {
    .Call(`_boostedintervals_interval_exp`, lower, upper)
}

interval_expm1 <- function(lower, upper) {
    .Call(`_boostedintervals_interval_expm1`, lower, upper)
}

interval_exp2 <- function(lower, upper) {
    .Call(`_boostedintervals_interval_exp2`, lower, upper)
}

interval_log <- function(lower, upper) {
    .Call(`_boostedintervals_interval_log`, lower, upper)
}

interval_log10 <- function(lower, upper) {
    .Call(`_boostedintervals_interval_log10`, lower, upper)
}

interval_log1p <- function(lower, upper) {
    .Call(`_boostedintervals_interval_log1p`, lower, upper)
}

interval_log2 <- function(lower, upper) {
    .Call(`_boostedintervals_interval_log2`, lower, upper)
}

interval_sqrt1pm1 <- function(lower, upper) {
    .Call(`_boostedintervals_interval_sqrt1pm1`, lower, upper)
}

interval_sin <- function(lower, upper) {
    .Call(`_boostedintervals_interval_sin`, lower, upper)
}

interval_cos <- function(lower, upper) {
    .Call(`_boostedintervals_interval_cos`, lower, upper)
}

interval_negate <- function(lower, upper) {
    .Call(`_boostedintervals_interval_negate`, lower, upper)
}

interval_width <- function(lower, upper) {
    .Call(`_boostedintervals_interval_width`, lower, upper)
}

interval_midpoint <- function(lower, upper) {
    .Call(`_boostedintervals_interval_midpoint`, lower, upper)
}

interval_median <- function(lower, upper) {
    .Call(`_boostedintervals_interval_median`, lower, upper)
}

interval_equals <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_equals`, lower1, upper1, lower2, upper2)
}

interval_less <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_less`, lower1, upper1, lower2, upper2)
}

interval_less_equal <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_less_equal`, lower1, upper1, lower2, upper2)
}

interval_greater <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_greater`, lower1, upper1, lower2, upper2)
}

interval_greater_equal <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_greater_equal`, lower1, upper1, lower2, upper2)
}

interval_overlaps <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_overlaps`, lower1, upper1, lower2, upper2)
}

interval_contains_interval <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_contains_interval`, lower1, upper1, lower2, upper2)
}

interval_contains_point <- function(lower, upper, point) {
    .Call(`_boostedintervals_interval_contains_point`, lower, upper, point)
}

interval_intersection <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_intersection`, lower1, upper1, lower2, upper2)
}

interval_union <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_union`, lower1, upper1, lower2, upper2)
}

interval_hypot <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_hypot`, lower1, upper1, lower2, upper2)
}

interval_abs <- function(lower, upper) {
    .Call(`_boostedintervals_interval_abs`, lower, upper)
}

interval_successor_scalar <- function(values, steps) {
    .Call(`_boostedintervals_interval_successor_scalar`, values, steps)
}

interval_predecessor_scalar <- function(values, steps) {
    .Call(`_boostedintervals_interval_predecessor_scalar`, values, steps)
}

interval_next_scalar <- function(values, steps) {
    .Call(`_boostedintervals_interval_next_scalar`, values, steps)
}

interval_prior_scalar <- function(values, steps) {
    .Call(`_boostedintervals_interval_prior_scalar`, values, steps)
}

interval_successor_interval <- function(lower, upper, steps) {
    .Call(`_boostedintervals_interval_successor_interval`, lower, upper, steps)
}

interval_predecessor_interval <- function(lower, upper, steps) {
    .Call(`_boostedintervals_interval_predecessor_interval`, lower, upper, steps)
}

interval_next_interval <- function(lower, upper, steps) {
    .Call(`_boostedintervals_interval_next_interval`, lower, upper, steps)
}

interval_prior_interval <- function(lower, upper, steps) {
    .Call(`_boostedintervals_interval_prior_interval`, lower, upper, steps)
}

interval_round_outward <- function(lower, upper, steps) {
    .Call(`_boostedintervals_interval_round_outward`, lower, upper, steps)
}

interval_round_inward <- function(lower, upper, steps) {
    .Call(`_boostedintervals_interval_round_inward`, lower, upper, steps)
}

interval_sqrt <- function(lower, upper) {
    .Call(`_boostedintervals_interval_sqrt`, lower, upper)
}

interval_pow <- function(lower, upper, exponent) {
    .Call(`_boostedintervals_interval_pow`, lower, upper, exponent)
}

interval_pow_numeric <- function(lower, upper, exponent) {
    .Call(`_boostedintervals_interval_pow_numeric`, lower, upper, exponent)
}

interval_scalar_pow <- function(base, lower, upper) {
    .Call(`_boostedintervals_interval_scalar_pow`, base, lower, upper)
}

interval_nth_root <- function(lower, upper, degree) {
    .Call(`_boostedintervals_interval_nth_root`, lower, upper, degree)
}

interval_pow1p <- function(lower, upper, exponent) {
    .Call(`_boostedintervals_interval_pow1p`, lower, upper, exponent)
}

interval_zero_in <- function(lower, upper) {
    .Call(`_boostedintervals_interval_zero_in`, lower, upper)
}

interval_is_empty <- function(lower, upper) {
    .Call(`_boostedintervals_interval_is_empty`, lower, upper)
}

interval_subset <- function(outer_lower, outer_upper, inner_lower, inner_upper) {
    .Call(`_boostedintervals_interval_subset`, outer_lower, outer_upper, inner_lower, inner_upper)
}

interval_proper_subset <- function(outer_lower, outer_upper, inner_lower, inner_upper) {
    .Call(`_boostedintervals_interval_proper_subset`, outer_lower, outer_upper, inner_lower, inner_upper)
}

interval_radius <- function(lower, upper) {
    .Call(`_boostedintervals_interval_radius`, lower, upper)
}

interval_norm <- function(lower, upper) {
    .Call(`_boostedintervals_interval_norm`, lower, upper)
}

interval_mag <- function(lower, upper) {
    .Call(`_boostedintervals_interval_mag`, lower, upper)
}

interval_mig <- function(lower, upper) {
    .Call(`_boostedintervals_interval_mig`, lower, upper)
}

interval_distance <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_distance`, lower1, upper1, lower2, upper2)
}

interval_bisect <- function(lower, upper) {
    .Call(`_boostedintervals_interval_bisect`, lower, upper)
}

interval_widen <- function(lower, upper, expansion) {
    .Call(`_boostedintervals_interval_widen`, lower, upper, expansion)
}

interval_tan <- function(lower, upper) {
    .Call(`_boostedintervals_interval_tan`, lower, upper)
}

interval_asin <- function(lower, upper) {
    .Call(`_boostedintervals_interval_asin`, lower, upper)
}

interval_acos <- function(lower, upper) {
    .Call(`_boostedintervals_interval_acos`, lower, upper)
}

interval_atan <- function(lower, upper) {
    .Call(`_boostedintervals_interval_atan`, lower, upper)
}

interval_sinh <- function(lower, upper) {
    .Call(`_boostedintervals_interval_sinh`, lower, upper)
}

interval_cosh <- function(lower, upper) {
    .Call(`_boostedintervals_interval_cosh`, lower, upper)
}

interval_tanh <- function(lower, upper) {
    .Call(`_boostedintervals_interval_tanh`, lower, upper)
}

interval_asinh <- function(lower, upper) {
    .Call(`_boostedintervals_interval_asinh`, lower, upper)
}

interval_acosh <- function(lower, upper) {
    .Call(`_boostedintervals_interval_acosh`, lower, upper)
}

interval_atanh <- function(lower, upper) {
    .Call(`_boostedintervals_interval_atanh`, lower, upper)
}

