# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interval_add <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_add`, lower1, upper1, lower2, upper2)
}

interval_subtract <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_subtract`, lower1, upper1, lower2, upper2)
}

interval_multiply <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_multiply`, lower1, upper1, lower2, upper2)
}

interval_divide <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_divide`, lower1, upper1, lower2, upper2)
}

interval_negate <- function(lower, upper) {
    .Call(`_boostedintervals_interval_negate`, lower, upper)
}

interval_width <- function(lower, upper) {
    .Call(`_boostedintervals_interval_width`, lower, upper)
}

interval_midpoint <- function(lower, upper) {
    .Call(`_boostedintervals_interval_midpoint`, lower, upper)
}

interval_equals <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_equals`, lower1, upper1, lower2, upper2)
}

interval_less <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_less`, lower1, upper1, lower2, upper2)
}

interval_less_equal <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_less_equal`, lower1, upper1, lower2, upper2)
}

interval_greater <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_greater`, lower1, upper1, lower2, upper2)
}

interval_greater_equal <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_greater_equal`, lower1, upper1, lower2, upper2)
}

interval_overlaps <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_overlaps`, lower1, upper1, lower2, upper2)
}

interval_contains_interval <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_contains_interval`, lower1, upper1, lower2, upper2)
}

interval_contains_point <- function(lower, upper, point) {
    .Call(`_boostedintervals_interval_contains_point`, lower, upper, point)
}

interval_intersection <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_intersection`, lower1, upper1, lower2, upper2)
}

interval_union <- function(lower1, upper1, lower2, upper2) {
    .Call(`_boostedintervals_interval_union`, lower1, upper1, lower2, upper2)
}

interval_abs <- function(lower, upper) {
    .Call(`_boostedintervals_interval_abs`, lower, upper)
}

interval_sqrt <- function(lower, upper) {
    .Call(`_boostedintervals_interval_sqrt`, lower, upper)
}

interval_pow <- function(lower, upper, exponent) {
    .Call(`_boostedintervals_interval_pow`, lower, upper, exponent)
}

interval_exp <- function(lower, upper) {
    .Call(`_boostedintervals_interval_exp`, lower, upper)
}

interval_log <- function(lower, upper) {
    .Call(`_boostedintervals_interval_log`, lower, upper)
}

interval_log10 <- function(lower, upper) {
    .Call(`_boostedintervals_interval_log10`, lower, upper)
}

interval_sin <- function(lower, upper) {
    .Call(`_boostedintervals_interval_sin`, lower, upper)
}

interval_cos <- function(lower, upper) {
    .Call(`_boostedintervals_interval_cos`, lower, upper)
}

